// IPFS utilities
export {
  initIPFS,
  getIPFSClient,
  uploadJSONToIPFS,
  uploadFileToIPFS,
  uploadBufferToIPFS,
  fetchJSONFromIPFS,
  fetchTextFromIPFS,
  fetchBlobFromIPFS,
  pinToIPFS,
  unpinFromIPFS,
  listPinnedContent,
  getIPFSGatewayUrl,
  checkIPFSConnection,
  getIPFSNodeInfo,
  type IPFSConfig,
} from './ipfs';

// Arweave utilities
export {
  initArweave,
  getArweaveClient,
  loadArweaveWallet,
  getWalletAddress,
  getWalletBalance,
  uploadJSONToArweave,
  uploadFileToArweave,
  uploadBufferToArweave,
  fetchJSONFromArweave,
  fetchTextFromArweave,
  fetchBlobFromArweave,
  getTransactionStatus,
  waitForConfirmation,
  getArweaveGatewayUrl,
  calculateUploadCost,
  checkArweaveConnection,
  getNetworkInfo,
  type ArweaveConfig,
} from './arweave';

// Starknet utilities
export {
  initStarknetProvider,
  getProvider,
  setContractAddresses,
  getBlogRegistryAddress,
  getSocialAddress,
  getPaymasterAddress,
  getSessionKeyManagerAddress,
  getPostCount,
  getPost,
  getPosts,
  publishPost,
  updatePost,
  deletePost,
  hasAccess,
  purchasePost,
  getPostPrice,
  getPostVersion,
  getPostVersionCount,
  getPostVersions,
  getCommentsForPost,
  addComment,
  addCommentWithSessionKey,
  likePost,
  unlikePost,
  hasLikedPost,
  getPostLikes,
  likeComment,
  unlikeComment,
  hasLikedComment,
  getSessionKeyNonce,
  getSessionKeyManager,
  setSessionKeyManager,
  calculateContentHash,
  isValidStarknetAddress,
  formatAddress,
  checkRPCConnection,
  getBlockNumber,
  type StarknetConfig,
  type PostVersion,
} from './starknet';
