// IPFS utilities
export {
  initIPFS,
  getIPFSClient,
  uploadJSONToIPFS,
  uploadFileToIPFS,
  uploadBufferToIPFS,
  fetchJSONFromIPFS,
  fetchTextFromIPFS,
  fetchBlobFromIPFS,
  pinToIPFS,
  unpinFromIPFS,
  listPinnedContent,
  getIPFSGatewayUrl,
  checkIPFSConnection,
  getIPFSNodeInfo,
  type IPFSConfig,
} from './ipfs';

// Arweave utilities
export {
  initArweave,
  getArweaveClient,
  loadArweaveWallet,
  getWalletAddress,
  getWalletBalance,
  uploadJSONToArweave,
  uploadFileToArweave,
  uploadBufferToArweave,
  fetchJSONFromArweave,
  fetchTextFromArweave,
  fetchBlobFromArweave,
  getTransactionStatus,
  waitForConfirmation,
  getArweaveGatewayUrl,
  calculateUploadCost,
  checkArweaveConnection,
  getNetworkInfo,
  type ArweaveConfig,
} from './arweave';

// Starknet utilities
export {
  initStarknetProvider,
  getProvider,
  setContractAddresses,
  getBlogRegistryAddress,
  getSocialAddress,
  getPaymasterAddress,
  getSessionKeyManagerAddress,
  getPostCount,
  getPost,
  getPosts,
  publishPost,
  updatePost,
  deletePost,
  hasAccess,
  purchasePost,
  getPostPrice,
  getPostVersion,
  getPostVersionCount,
  getPostVersions,
  getCommentsForPost,
  getCommentCountForPost,
  addComment,
  addCommentWithSessionKey,
  likePost,
  unlikePost,
  hasLikedPost,
  getPostLikes,
  likeComment,
  unlikeComment,
  hasLikedComment,
  getSessionKeyNonce,
  getSessionKeyManager,
  setSessionKeyManager,
  calculateContentHash,
  isValidStarknetAddress,
  formatAddress,
  checkRPCConnection,
  getBlockNumber,
  // Extended post functions (Twitter-like)
  POST_TYPE_TWEET,
  POST_TYPE_THREAD,
  POST_TYPE_ARTICLE,
  publishPostExtended,
  publishTweet,
  publishReply,
  startThread,
  continueThread,
  pinPost,
  unpinPost,
  getPinnedPost,
  getPostsByType,
  getPostReplies,
  getReplyCount,
  getThreadPosts,
  getThreadPostCount,
  getPostsCountByType,
  getPublishCooldown,
  setPublishCooldown,
  // Role Registry
  getRoleRegistryAddress,
  getUserRole,
  hasMinRole,
  getRoleStats,
  grantRole,
  revokeRole,
  registerUser,
  canPublishImmediately,
  canManageUsers,
  ROLE_READER,
  ROLE_WRITER,
  ROLE_CONTRIBUTOR,
  ROLE_MODERATOR,
  ROLE_EDITOR,
  ROLE_ADMIN,
  ROLE_OWNER,
  ROLE_NAMES,
  // Reputation
  getReputationAddress,
  getUserReputation,
  getUserPoints,
  getUserLevel,
  getUserBadges,
  hasBadge,
  getReputationStats,
  BADGE_FIRST_POST,
  BADGE_PROLIFIC_WRITER,
  BADGE_CENTURY_CLUB,
  BADGE_FEATURED_AUTHOR,
  BADGE_CONVERSATIONALIST,
  BADGE_BELOVED,
  BADGE_EARLY_ADOPTER,
  BADGE_VERIFIED,
  BADGE_TOP_WRITER,
  BADGE_PREMIUM_AUTHOR,
  BADGE_TRUSTED,
  BADGE_GUARDIAN,
  BADGE_INFO,
  LEVEL_NAMES,
  type StarknetConfig,
  type PostVersion,
  type UserRoleInfo,
  type RoleStats,
  type UserReputation,
} from './starknet';

// Contract ABIs (for direct Contract usage)
export { default as followsAbi } from './abis/follows.json';
